name: ecommerce_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.3.4

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider_plus:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_slidable:
  auto_size_text:
  colornames:
  flutter_svg:
  flutter_native_splash:
  readmore:
  smooth_page_indicator:
  get_it: ^7.6.7
  injectable: ^2.3.5
  dio: ^5.6.0
  either_dart: 1.0.0
  internet_connection_checker: ^2.0.0
  flutter_bloc: ^8.1.6
  fluttertoast: ^8.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  injectable_generator: ^2.4.2
  #  injectable_generator: 2.6.2
  build_runner: ^2.4.9


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg_images/



  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-.ttf



